### ISSUE TITLE
Remove raw use of parameterized class 'Map.Entry' 

### ISSUE THREAD

**Issue by andreyTheGreatest** [Hiaza/labs_mipz#2]
Define parametrized type explicitly [here](https://github.com/Hiaza/labs_mipz/blob/7a58a452f870c79c4469da5e62df03e00ec28bbb/lab1/src/main/java/models/City.java#L27) and [here ](https://github.com/Hiaza/labs_mipz/blob/7a58a452f870c79c4469da5e62df03e00ec28bbb/lab1/src/main/java/models/Placer.java#L109) and also further in Placer.java
Thus conversions are unnecessary

**Comment by Hiaza** [comment]
Thank you @andreyTheGreatest , [changed](https://github.com/Hiaza/labs_mipz/pull/1/commits/d2e7068fe862a46c0e6a04a2e448b99010bb882e))
