### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by andreyTheGreatest** [Hiaza/labs_mipz#3]
It is better to lean towards one naming convention throughout the project
Camel case is used everywhere except [here](https://github.com/Hiaza/labs_mipz/blob/7a58a452f870c79c4469da5e62df03e00ec28bbb/lab1/src/main/java/models/Country.java#L9), [here](https://github.com/Hiaza/labs_mipz/blob/7a58a452f870c79c4469da5e62df03e00ec28bbb/lab1/src/main/java/models/Placer.java#L110) and [here](https://github.com/Hiaza/labs_mipz/blob/7a58a452f870c79c4469da5e62df03e00ec28bbb/lab1/src/main/java/models/Placer.java#L120) is snake case

**Comment by Hiaza** [comment]
Yea, it makes sense. [Changed](https://github.com/Hiaza/labs_mipz/pull/1/commits/1a8008fa8e30969d4ad90760396743100950a39d) according to Camel case convention
