### ISSUE TITLE
Java streams

### ISSUE THREAD

**Issue by andreyTheGreatest** [Hiaza/labs_mipz#4]
[isComleted](https://github.com/Hiaza/labs_mipz/blob/7a58a452f870c79c4469da5e62df03e00ec28bbb/lab1/src/main/java/models/City.java#L25) functions are more elegant using streams and allMatch function, but that's just me being picky :)

**Comment by Hiaza** [comment]
Agree, looks much better :) [Changed it here](https://github.com/Hiaza/labs_mipz/pull/1/commits/5d362fbc0330296ffe05b9407b5c97a17edd9cea)
