### ISSUE TITLE
Exception message issue

### ISSUE THREAD

**Issue by IanaKhitsko** [Hiaza/labs_mipz#5]
https://github.com/Hiaza/labs_mipz/blob/fbf4a3d31878045a5091575c555cb797e012d421/lab1/src/main/java/models/Country.java#L18

What if the constant will be changed? You will probably need to chang the text here

**Comment by Hiaza** [comment]
Thank you, nice catch! Changed in this [commit](https://github.com/Hiaza/labs_mipz/commit/ab470c267d31f25d3d4d7eab4ddf3e056327424d).
