### ISSUE TITLE
Remove local flag

### ISSUE THREAD

**Issue by IanaKhitsko** [Hiaza/labs_mipz#6]
https://github.com/Hiaza/labs_mipz/blob/fbf4a3d31878045a5091575c555cb797e012d421/lab1/src/main/java/models/Placer.java#L39

                    if (country.isCompleted()) {
                        results.putIfAbsent(country.name, i);
                    }
                    else {
                          isCompleted = false;
                    }

**Comment by Hiaza** [comment]
Yea, we totally can change it. Thanks!
Changed in this [commit](https://github.com/Hiaza/labs_mipz/commit/ab470c267d31f25d3d4d7eab4ddf3e056327424d).
