### ISSUE TITLE
Lambda?

### ISSUE THREAD

**Issue by IanaKhitsko** [Hiaza/labs_mipz#7]
https://github.com/Hiaza/labs_mipz/blob/fbf4a3d31878045a5091575c555cb797e012d421/lab1/src/main/java/models/Placer.java#L98-L99

Can we make it as lambda with x,y as params and get rid of this cycle ?

**Comment by Hiaza** [comment]
I tried, but I didn't catch how to replace It with lambda. I refactored the code and added lambda, but I'm not sure is that new change is acceptable for you. Please take a look [here](https://github.com/Hiaza/labs_mipz/commit/ab470c267d31f25d3d4d7eab4ddf3e056327424d).

If the change is not acceptable, please provide me more tips..
